name: Update submodules
on:
  push: { branches: [ all ] }
  workflow_dispatch:
    inputs:
      merge_into_server:
        description: "Merge `all` into `server`"
        type: boolean
        default: false
jobs:
  update:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - name: Update submodules
        uses: runsascoded/update-submodules@v1
        id: update
        with:
          branch: ${{ github.ref_name }}
          token: ${{ github.token }}
      - name: "Merge `all` into `server`"
        run: gh api -XPOST /repos/$GITHUB_REPOSITORY/merges -fbase=server -fhead=all '-fcommit_message=Merge `all` into `server`'
        if: (github.ref_name == 'all' && steps.update.outputs.commit) || github.event.inputs.merge_into_server
        env:
          GH_TOKEN: ${{ github.token }}